# Generated by Django 5.2.4 on 2025-07-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0002_player_is_ir_player_is_to'),
	]

	operations = [
		migrations.AddField(
			model_name='player',
			name='nba_id',
			field=models.CharField(blank=True, max_length=20, null=True, unique=True),
		),
	]
