# Generated by Django 5.2.4 on 2025-07-07 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0005_notification_updated_at_user_is_approved"),
	]

	operations = [
		migrations.AlterField(
			model_name="player",
			name="contract_duration",
			field=models.PositiveIntegerField(
				blank=True,
				null=True,
				validators=[
					django.core.validators.MinValueValidator(1),
					django.core.validators.MaxValueValidator(10),
				],
			),
		),
		migrations.AlterField(
			model_name="player",
			name="salary",
			field=models.DecimalField(
				blank=True,
				decimal_places=2,
				max_digits=10,
				null=True,
				validators=[django.core.validators.MinValueValidator(0)],
			),
		),
	]
