# Generated by Django 5.2.4 on 2025-07-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0007_alter_player_options_rename_name_player_first_name_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='player',
			name='real_team',
			field=models.CharField(blank=True, max_length=100, null=True),
		),
	]
