# Generated by Django 5.2.4 on 2025-07-17 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0008_player_real_team"),
	]

	operations = [
		migrations.CreateModel(
			name="NBATeam",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("city", models.CharField(max_length=100)),
				("name", models.CharField(max_length=100)),
				("abbreviation", models.CharField(max_length=10)),
			],
		),
		migrations.AlterField(
			model_name="player",
			name="real_team",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="players",
				to="core.nbateam",
			),
		),
	]
