# Generated by Django 5.2.4 on 2025-07-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("core", "0009_nbateam_alter_player_real_team"),
	]

	operations = [
		migrations.AddField(
			model_name="player",
			name="metadata",
			field=models.JSONField(blank=True, default=dict, null=True),
		),
	]
