from django.db import migrations


def data_migration(apps, schema_editor):
	User = apps.get_model('core', 'User')

	data = [
		{
			'password': 'pbkdf2_sha256$1000000$aPiC39GLjtT1uVrCiPr1C1$PamkmfxCq6nT2QiKjSk6BJlcCeNY0SNHzUCtYFfh3vw=',
			'username': 'gtkacz',
			'is_superuser': True,
			'first_name': 'Gabriel',
			'last_name': 'Mitelman Tkacz',
			'email': 'gmtkacz@proton.me',
			'is_staff': True,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'lucas.cunha',
			'is_superuser': False,
			'first_name': 'Lucas',
			'last_name': 'Cunha',
			'email': 'placeholder@gmail.com',
			'is_staff': True,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'matheus.pacheco',
			'is_superuser': False,
			'first_name': 'Matheus',
			'last_name': 'Pacheco',
			'email': 'placeholder@gmail.com',
			'is_staff': True,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'felipe.murakoshi',
			'is_superuser': False,
			'first_name': 'Felipe',
			'last_name': 'Murakoshi',
			'email': 'placeholder@gmail.com',
			'is_staff': True,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'arthur.wippel',
			'is_superuser': False,
			'first_name': 'Arthur',
			'last_name': 'Wippel',
			'email': 'placeholder@gmail.com',
			'is_staff': True,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'adriano.andrade',
			'is_superuser': False,
			'first_name': 'Adriano',
			'last_name': 'Andrade',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'airton.ferreira',
			'is_superuser': False,
			'first_name': 'Airton',
			'last_name': 'Ferreira',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'cesar.castro',
			'is_superuser': False,
			'first_name': 'Cesar',
			'last_name': 'de Castro',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'fabio.henrique',
			'is_superuser': False,
			'first_name': 'Fábio',
			'last_name': 'Henrique',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'gabriel.cardoso',
			'is_superuser': False,
			'first_name': 'Gabriel',
			'last_name': 'Cardoso',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'gian.bachstein',
			'is_superuser': False,
			'first_name': 'Gian',
			'last_name': 'Bachstein',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'guilherme.bender',
			'is_superuser': False,
			'first_name': 'Guilherme',
			'last_name': 'Bender',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'jeferson.costa',
			'is_superuser': False,
			'first_name': 'Jeferson',
			'last_name': 'Costa',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'lucas.sodre',
			'is_superuser': False,
			'first_name': 'Lucas',
			'last_name': 'Sodré',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'pedro.alencar',
			'is_superuser': False,
			'first_name': 'Pedro',
			'last_name': 'Alencar',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'rafael.esbizero',
			'is_superuser': False,
			'first_name': 'Rafael',
			'last_name': 'Esbizero',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'roberto.almeida',
			'is_superuser': False,
			'first_name': 'Roberto',
			'last_name': 'Almeida',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
		{
			'password': 'pbkdf2_sha256$1000000$zpUbhypgXn5u6mRQVF5iSM$XjB/VoxLtQ6eNTm3/IBcCJST0h6GwIA9JVBj+w/cjfo=',
			'username': 'vitor.gutterres',
			'is_superuser': False,
			'first_name': 'Vitor',
			'last_name': 'Gutterres',
			'email': 'placeholder@gmail.com',
			'is_staff': False,
			'is_active': True,
			'is_approved': True,
		},
	]

	for datum in data:
		User.objects.update_or_create(**datum)


class Migration(migrations.Migration):
	dependencies = [
		('core', '0011_remove_player_contract_duration_remove_player_salary_and_more'),
	]

	operations = [
		migrations.RunPython(data_migration, atomic=True),
	]
