# Generated by Django 5.2.4 on 2025-07-22 22:09

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('core', '0019_alter_team_avatar'),
	]

	operations = [
		migrations.RemoveField(
			model_name='team',
			name='avatar',
		),
	]
