# Generated by Django 5.2.4 on 2025-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0021_notification_level_notification_priority'),
	]

	operations = [
		migrations.AlterField(
			model_name='notification',
			name='priority',
			field=models.PositiveIntegerField(
				default=1,
				help_text='Priority of the notification, higher number means higher priority',
			),
		),
	]
