# Generated by Django 5.2.4 on 2025-11-03 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_player_options_trade_tradeasset_tradeoffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('veto', 'Veto')], help_text='Vote decision: approve or veto', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional reasoning or comments for the vote')),
                ('voted_at', models.DateTimeField(auto_now_add=True, help_text='When this vote was cast')),
                ('commissioner', models.ForeignKey(help_text='Commissioner casting this vote (must be is_staff or is_superuser)', on_delete=django.db.models.deletion.CASCADE, related_name='trade_votes', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(help_text='The trade being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.trade')),
            ],
            options={
                'verbose_name': 'Trade Approval',
                'verbose_name_plural': 'Trade Approvals',
                'ordering': ('-voted_at',),
                'indexes': [models.Index(fields=['trade', 'vote'], name='trade_approval_trade_vote_idx'), models.Index(fields=['commissioner'], name='trade_approval_comm_idx'), models.Index(fields=['-voted_at'], name='trade_approval_date_idx')],
                'unique_together': {('trade', 'commissioner')},
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Trade Created'), ('modified', 'Trade Modified'), ('proposed', 'Trade Proposed'), ('accepted', 'Team Accepted'), ('rejected', 'Team Rejected'), ('countered', 'Counter Offer'), ('cancelled', 'Trade Cancelled'), ('approval_requested', 'Approval Requested'), ('commissioner_voted', 'Commissioner Voted'), ('approved', 'Commissioner Approved'), ('vetoed', 'Commissioner Vetoed'), ('executed', 'Trade Executed')], help_text='Type of event that occurred', max_length=30)),
                ('message', models.TextField(blank=True, help_text='Human-readable description or notes about this event')),
                ('assets_snapshot', models.JSONField(blank=True, help_text='JSON snapshot of trade assets at this point in time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this event occurred')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event (None for system events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_actions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team involved in this event (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_history', to='core.team')),
                ('trade', models.ForeignKey(help_text='The trade this event is for', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.trade')),
            ],
            options={
                'verbose_name': 'Trade History',
                'verbose_name_plural': 'Trade Histories',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['trade', '-created_at'], name='trade_history_trade_date_idx'), models.Index(fields=['event_type'], name='trade_history_event_type_idx'), models.Index(fields=['actor'], name='trade_history_actor_idx')],
            },
        ),
    ]
