# Generated by Django 5.2.4 on 2025-11-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tradeapproval_tradehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeApproval',
        ),
        migrations.DeleteModel(
            name='TradeAsset',
        ),
        migrations.DeleteModel(
            name='TradeHistory',
        ),
        migrations.DeleteModel(
            name='TradeOffer',
        ),
    ]
