# Generated by Django 5.2.4 on 2025-11-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_tradeasset_trade_remove_tradehistory_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, help_text="User's cellphone number", max_length=31),
        ),
    ]
