# Generated by Django 5.2.4 on 2025-11-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_cellphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cellphone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, help_text="User's cellphone country code", max_length=8),
        ),
    ]
