# Generated by Django 5.2.4 on 2025-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_cellphone_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, choices=[('G', 'Guard'), ('F', 'Forward'), ('C', 'Center')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
