# Generated by Django 5.2.4 on 2025-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_player_secondary_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_to',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
