# Generated by Django 5.2.4 on 2026-07-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_notification_redirect_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google account subject identifier (sub claim) for linked Google sign-in",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
