# Generated by Django 5.2.4 on 2026-07-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_user_google_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="espn_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
