# Generated by Django 5.2.4 on 2025-07-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("draft", "0003_remove_draft_is_snake_draft"),
	]

	operations = [
		migrations.AddField(
			model_name="draft",
			name="is_snake",
			field=models.BooleanField(default=False),
		),
	]
