# Generated by Django 5.2.4 on 2025-07-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('draft', '0006_rename_is_snake_draft_is_league_draft'),
	]

	operations = [
		migrations.AlterField(
			model_name='draft',
			name='year',
			field=models.PositiveIntegerField(),
		),
		migrations.AlterUniqueTogether(
			name='draft',
			unique_together={('year', 'is_league_draft')},
		),
	]
