# Generated by Django 5.2.4 on 2025-07-18 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0015_remove_player_is_rfa_remove_player_is_to_and_more'),
		('draft', '0009_draftpick_salary'),
	]

	operations = [
		migrations.RemoveField(
			model_name='draftpick',
			name='salary',
		),
		migrations.AddField(
			model_name='draftpick',
			name='contract',
			field=models.OneToOneField(
				blank=True,
				help_text='Contract associated with the drafted player',
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name='draft_pick',
				to='core.contract',
			),
		),
	]
