# Generated by Django 5.2.4 on 2025-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_player_slug'),
        ('draft', '0010_remove_draftpick_salary_draftpick_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='is_current',
            field=models.BooleanField(default=False),
        )
    ]
