# Generated by Django 5.2.4 on 2025-07-23 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('core', '0020_remove_team_avatar'),
		('draft', '0014_future_picks'),
	]

	operations = [
		migrations.CreateModel(
			name='DraftQueue',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'autopick_enabled',
					models.BooleanField(
						default=False, help_text='Enable auto-pick from queue'
					),
				),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				(
					'queue_items',
					models.JSONField(
						blank=True,
						default=list,
						help_text='List of player IDs in the draft queue',
						null=True,
					),
				),
				(
					'draft',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='team_queues',
						to='draft.draft',
					),
				),
				(
					'team',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='draft_queues',
						to='core.team',
					),
				),
			],
			options={
				'unique_together': {('team', 'draft')},
			},
		),
	]
