# Generated by Django 5.2.4 on 2025-10-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_player_options_trade_tradeasset_tradeoffer_and_more'),
        ('draft', '0016_alter_draftqueue_autopick_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterModelOptions(
            name='draftpick',
            options={'ordering': ('draft', 'pick')},
        ),
        migrations.AlterModelOptions(
            name='pick',
            options={'ordering': ('draft_year', 'round_number')},
        ),
        migrations.RemoveField(
            model_name='pick',
            name='protections',
        ),
        migrations.AddField(
            model_name='pick',
            name='actual_pick_number',
            field=models.PositiveIntegerField(blank=True, help_text='Actual pick number after lottery/standings (1-30 for round 1)', null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='is_conveyed',
            field=models.BooleanField(default=True, help_text='Whether this pick conveyed to current_team or was protected'),
        ),
        migrations.AddField(
            model_name='pick',
            name='protection_range_end',
            field=models.PositiveIntegerField(blank=True, help_text='End of protected pick range (e.g., 5 for top-5 protected)', null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='protection_range_start',
            field=models.PositiveIntegerField(blank=True, help_text='Start of protected pick range (e.g., 1 for top-5 protected)', null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='protection_type',
            field=models.CharField(choices=[('none', 'No Protection'), ('swap_best', 'Swap if Best'), ('swap_worst', 'Swap if Worst'), ('doesnt_convey', "Doesn't Convey")], default='none', help_text='Type of protection on this pick', max_length=20),
        ),
        migrations.AddField(
            model_name='pick',
            name='rollover_year',
            field=models.PositiveIntegerField(blank=True, help_text="Year pick rolls over to if it doesn't convey", null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='swap_target_pick',
            field=models.ForeignKey(blank=True, help_text='Pick to swap with if protection is triggered (for swap_best/swap_worst)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_sources', to='draft.pick'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['draft_year', 'current_team'], name='draft_pick_draft_y_2037c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['protection_type'], name='draft_pick_protect_0f7d6a_idx'),
        ),
    ]
