# Generated by Django 5.2.4 on 2025-11-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0017_alter_draft_options_alter_draftpick_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pick',
            name='draft_pick_protect_0f7d6a_idx',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='protection_range_end',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='protection_range_start',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='protection_type',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='rollover_year',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='swap_target_pick',
        ),
    ]
