# Generated by Django 5.2.4 on 2025-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0018_remove_pick_draft_pick_protect_0f7d6a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='is_conveyed',
        ),
        migrations.AddField(
            model_name='pick',
            name='protection',
            field=models.CharField(choices=[('unprotected', 'UNPROTECTED'), ('top_x', 'TOP_X'), ('swap_best', 'SWAP_BEST'), ('swap_worst', 'SWAP_WORST')], default='unprotected', max_length=11),
        ),
    ]
