# Generated by Django 5.2.4 on 2025-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0019_remove_pick_is_conveyed_pick_protection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='actual_pick_number',
        ),
        migrations.AddField(
            model_name='pick',
            name='protection_metadata',
            field=models.JSONField(blank=True, help_text="Additional data related to the pick's protection (e.g., value of X for TOP_X protection)", null=True),
        ),
    ]
