# Generated by Django 5.2.4 on 2025-11-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0020_remove_pick_actual_pick_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='protection_conveyed',
            field=models.BooleanField(default=False, help_text="Indicates if the pick's protection has been conveyed to the receiving team"),
        ),
    ]
