# Generated by Django 5.2.4 on 2025-11-06 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0025_remove_tradeasset_trade_remove_tradehistory_trade_and_more'),
        ('draft', '0019_remove_pick_is_conveyed_pick_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='succeeded_by', to='trade.trade')),
                ('participants', models.ManyToManyField(related_name='trades', to='core.team')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_created', to='core.team')),
            ],
            options={
                'ordering': ('created_at', 'updated_at'),
            },
        ),
        migrations.CreateModel(
            name='TradeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('player', 'Player'), ('pick', 'Draft Pick')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.pick')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_assets', to='core.team')),
                ('player_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_assets', to='core.team')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='trade.trade')),
            ],
            options={
                'ordering': ('created_at', 'updated_at'),
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['sender'], name='trade_trade_sender__e420c9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['parent'], name='trade_trade_parent__699366_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeasset',
            index=models.Index(fields=['owner', 'receiver'], name='trade_trade_owner_i_ef7e34_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeasset',
            index=models.Index(fields=['trade'], name='trade_trade_trade_i_9e959a_idx'),
        ),
    ]
