# Generated by Django 5.2.4 on 2025-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_tradeasset_trade_remove_tradehistory_trade_and_more'),
        ('draft', '0019_remove_pick_is_conveyed_pick_protection'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tradeasset',
            name='trade_trade_owner_i_ef7e34_idx',
        ),
        migrations.RenameField(
            model_name='tradeasset',
            old_name='owner',
            new_name='sender',
        ),
        migrations.AddIndex(
            model_name='tradeasset',
            index=models.Index(fields=['sender', 'receiver'], name='trade_trade_sender__72353e_idx'),
        ),
    ]
