# Generated by Django 5.2.4 on 2025-11-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_cellphone'),
        ('draft', '0019_remove_pick_is_conveyed_pick_protection'),
        ('trade', '0002_remove_tradeasset_trade_trade_owner_i_ef7e34_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeasset',
            name='draft_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_assets', to='draft.pick'),
        ),
        migrations.AlterField(
            model_name='tradeasset',
            name='player_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_assets', to='core.contract'),
        ),
    ]
