# Generated by Django 5.2.4 on 2025-11-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_player_secondary_position'),
        ('trade', '0003_alter_tradeasset_draft_pick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('sent', 'SENT'), ('rejected', 'REJECTED'), ('counteroffer', 'COUNTEROFFER'), ('accepted', 'ACCEPTED'), ('vetoed', 'VETOED'), ('approved', 'APPROVED')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_actions', to='core.team')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='trade.trade')),
            ],
            options={
                'ordering': ('created_at', 'updated_at'),
                'indexes': [models.Index(fields=['trade'], name='trade_trade_trade_i_9873d2_idx'), models.Index(fields=['trade', 'actioned_by'], name='trade_trade_trade_i_911cfb_idx'), models.Index(fields=['status', 'actioned_by'], name='trade_trade_status_0f01b2_idx')],
                'unique_together': {('trade', 'actioned_by', 'status')},
            },
        ),
    ]
