# Generated by Django 5.2.4 on 2025-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_tradestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestatus',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('sent', 'SENT'), ('rejected', 'REJECTED'), ('counteroffer', 'COUNTEROFFER'), ('accepted', 'ACCEPTED'), ('pending', 'PENDING'), ('vetoed', 'VETOED'), ('approved', 'APPROVED')], max_length=20),
        ),
    ]
