# Generated by Django 5.2.4 on 2025-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_tradestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradestatus',
            name='status',
            field=models.CharField(choices=[('sent', 'SENT'), ('rejected', 'REJECTED'), ('accepted', 'ACCEPTED'), ('pending', 'PENDING'), ('vetoed', 'VETOED'), ('approved', 'APPROVED')], max_length=20),
        ),
    ]
