# Generated by Django 5.2.4 on 2026-07-21 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0031_player_espn_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(unique=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("index",),
            },
        ),
        migrations.CreateModel(
            name="NbaGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espn_event_id", models.CharField(max_length=20, unique=True)),
                ("starts_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("final", "Final (box not yet stable)"),
                            ("settled", "Settled"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                ("period", models.PositiveSmallIntegerField(default=0)),
                ("clock", models.CharField(blank=True, max_length=10)),
                (
                    "settle_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the last fetched box, for stability detection",
                        max_length=64,
                    ),
                ),
                (
                    "away",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="away_games",
                        to="core.nbateam",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_games",
                        to="core.nbateam",
                    ),
                ),
                (
                    "scoring_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="scoring.scoringperiod",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at",),
            },
        ),
        migrations.CreateModel(
            name="PlayerGameLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_stats", models.JSONField(default=dict)),
                (
                    "fpts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_final", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="scoring.nbagame",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_lines",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("formula_text", models.TextField()),
                (
                    "weights_json",
                    models.JSONField(
                        blank=True,
                        help_text="Grid-mode weights, kept only for round-trip editing",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=20)),
                ("old_value", models.FloatField()),
                ("new_value", models.FloatField()),
                ("applied", models.BooleanField(default=False)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="scoring.playergameline",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="playergameline",
            constraint=models.UniqueConstraint(
                fields=("player", "game"), name="unique_line_per_player_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_scoring_rule",
            ),
        ),
    ]
