"""
Django settings for ftt project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from os import environ, path
from pathlib import Path

from box import Box
from django.core.management.utils import get_random_secret_key
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
ENV = Box(environ)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV.ENVIRONMENT == 'development'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	'rest_framework_simplejwt',
	'rest_framework_simplejwt.token_blacklist',
	'corsheaders',
	'puml_generator',
	'drf_spectacular',
	'django_extensions',
	'sslserver',
	'django_filters',
	'crispy_forms',
	'crispy_bootstrap4',
	'core',
	'draft',
	'auction',
]

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ftt.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'ftt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'


REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework_simplejwt.authentication.JWTAuthentication',
	],
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticatedOrReadOnly'
		if DEBUG
		else 'rest_framework.permissions.IsAuthenticated',
	],
	'DEFAULT_FILTER_BACKENDS': [
		'django_filters.rest_framework.DjangoFilterBackend',
		'rest_framework.filters.OrderingFilter',
		'rest_framework.filters.SearchFilter',
	],
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
	'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
	'PAGE_SIZE': 20,
}

SPECTACULAR_SETTINGS = {
	'TITLE': 'Fantasy Trash Talk API',
	'DESCRIPTION': 'A comprehensive REST API for managing dynasty-style fantasy basketball leagues',
	'VERSION': '1.0.0',
	'SERVE_INCLUDE_SCHEMA': False,
	'COMPONENT_SPLIT_REQUEST': True,
	'SCHEMA_PATH_PREFIX': '/api/',
	'TAGS': [
		{
			'name': 'Authentication',
			'description': 'User registration and authentication endpoints',
		},
		{'name': 'Users', 'description': 'User management operations'},
		{'name': 'Teams', 'description': 'Team management and analytics'},
		{'name': 'Players', 'description': 'Player roster management'},
		{'name': 'Draft Capital', 'description': 'Draft pick assets and trading'},
		{'name': 'Drafts', 'description': 'Draft events and live drafting'},
		{'name': 'Draft Positions', 'description': 'Draft order and pick management'},
	],
	'SWAGGER_UI_SETTINGS': {
		'deepLinking': True,
		'persistAuthorization': True,
		'displayOperationId': True,
	},
	'PREPROCESSING_HOOKS': [],
	'POSTPROCESSING_HOOKS': [],
}

SIMPLE_JWT = {
	'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
	'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
	'UPDATE_LAST_LOGIN': True,
	'SIGNING_KEY': get_random_secret_key(),
}

CORS_ALLOW_ALL_ORIGINS = DEBUG

if not CORS_ALLOW_ALL_ORIGINS:
	CORS_ALLOWED_ORIGINS = ['https://gtkacz.github.io', 'http://localhost']

CORS_ALLOW_HEADERS = (
	*default_headers,
	'bypass-tunnel-reminder',
)

LEAGUE_SETTINGS = Box(
	{
		'SALARY_CAP': int(ENV.SALARY_CAP),
		'MIN_PLAYER_CAP': int(ENV.MIN_PLAYER_CAP),
		'MAX_PLAYER_CAP': int(ENV.MAX_PLAYER_CAP),
	}
)

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'handlers': {
		'file': {
			'level': 'INFO',
			'class': 'logging.FileHandler',
			'filename': 'auto_draft.log',
		},
	},
	'loggers': {
		'draft.management.commands.auto_draft_picker': {
			'handlers': ['file'],
			'level': 'INFO',
			'propagate': True,
		},
	},
}
